services:
  db:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "daily-diet"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      - /mnt/c/Users/iurid/Desktop/DEV/rocketseat/mysql:/var/lib/mysql
